/*
SERIAL it will create a sequence object and set the next value generated by 
the sequence as the default value for the column
*/
CREATE TABLE account(
	user_id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(250) UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL,
	last_login TIMESTAMP
);

CREATE TABLE job(
	job_id SERIAL PRIMARY KEY,
	job_name VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE account_job1(
	user_id INTEGER REFERENCES account(user_id),
	job_id INTEGER REFERENCES job(job_id),
	hire_date TIMESTAMP
);
-- account
SELECT * FROM account
	
INSERT INTO account(username,password,email,created_on)
VALUES('Jose','password','jose@mail.com',CURRENT_TIMESTAMP)
	
-- job
SELECT * FROM job
	
INSERT INTO job(job_name)
VALUES('Astronaut')
INSERT INTO job(job_name)
VALUES('President')

INSERT INTO account_job1(user_id,job_id,hire_date)
VALUES (1,1,CURRENT_TIMESTAMP)
SELECT * FROM account_job1
/* Give an error
INSERT INTO account_job1(user_id,job_id,hire_date)
VALUES (10,10,CURRENT_TIMESTAMP)
*/

INSERT INTO account(username, password,email,created_on)
VALUES ('Ritesh','ladki_bahin','bahin@mail.com',CURRENT_TIMESTAMP)
SELECT * FROM account

INSERT INTO job(job_name)
VALUES ('Data_Scientist')
SELECT * FROM job

UPDATE account
SET last_login = CURRENT_TIMESTAMP

UPDATE account
SET last_login = created_on 

SELECT * FROM account_job1
UPDATE account_job1
SET hire_date = account.created_on
FROM account
WHERE account_job1.user_id = account.user_id









